version: '3.1'
services:
  acme-app:
    image: ruby
    hostname: acme-app
    container_name: acme-app
    dns: 8.8.8.8
    volumes:
      - ./data:/root/data
    tty: true
    command: sh /root/data/generate.sh    
